
export const USER_POST_REQUEST = "USER_POST_REQUEST";
export const USER_POST_SUCCESS = "USER_POST_SUCCESS";
export const USER_POST_FAILURE = "USER_POST_FAILURE";

export const USER_STORIES_REQUEST = "USER_STORIES_REQUEST";
export const USER_STORIES_SUCCESS = "USER_STORIES_SUCCESS";
export const USER_STORIES_FAILURE = "USER_STORIES_FAILURE";